name: SlimefunFix
main: com.ram.slimefunfix.Main
version: 1.0
author: Ram
depends: [Slimefun]

commands:
  slimefunfix:
    aliases: [sff]

permissions:
  slimefunfix.reload:
    default: op
